blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('password-generator/', include("pwgenerator.urls"), name='pwgenerator'),
    path('todo/', include("todo.urls"), name='todo'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    # Todos
    path('', views.home, name='home'),
    path('create/', views.createtodo, name='createtodo'),
    path('current/', views.currenttodos, name='currenttodos'),
    path('completed/', views.completedtodos, name='completedtodos'),
    path('todo/<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/complete', views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', views.deletetodo, name='deletetodo'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True) # not required!
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title   # changes the blogpost name to the specific title

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important'] # fields to be shown in the create to do page

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import TodoForm
from .models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'todo/home.html')

def signupuser(request):
    if request.method == 'GET':
        return render(request, "todo/signupuser.html", {'form': UserCreationForm()})

    # create a new user
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('todo:currenttodos')    # redirects to the name='currenttodos' in urls.py
            except IntegrityError:
                return render(request, "todo/signupuser.html",
                              {'form': UserCreationForm(), 'error': 'Username already taken. Please choose a new username.'})

        # Passwords didn't match
        else:
            return render(request, "todo/signupuser.html", {'form': UserCreationForm(),
                                                            'error': 'Password did not match'})

def loginuser(request):
        if request.method == "GET":
            return render(request, "todo/loginuser.html", {'form': AuthenticationForm()})
        else:
            user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
            if user is None:
                return render(request, "todo/loginuser.html", {'form': AuthenticationForm(),
                                                               'error': 'Username or password did not match.'})
            else:
                login(request, user)
                return redirect('todo:currenttodos')

@login_required
def logoutuser(request):
    if request.method == "POST":    # blocks the 'auto-logout' of the user, performed by Chrome
        logout(request)
        return redirect('todo:home')

@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form': TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/createtodo.html', {'form': TodoForm(),
                                                            'error': 'Bad data passed in. Try again.'})
@login_required
def currenttodos(request):
    todos = Todo.objects.filter(user=request.user,
                                datecompleted__isnull=True)  # get just the user's todos and check if the todo is completed.
    return render(request, 'todo/currenttodos.html', {'todos': todos})

@login_required
def completedtodos(request):
    todos = Todo.objects.filter(user=request.user,
                                datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'todo/completedtodos.html', {'todos': todos})

@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk,
                             user=request.user)   # user=request.user: only the todos of user can be edited
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form, 'error': 'Bad info.'})

@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk,
                             user=request.user)  # user=request.user: only the todos of user can be edited
    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('todo:currenttodos')

@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:currenttodos')

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'todo/Logo.png' %}">
</head>
<body>
{% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'todo:home' %}">
          <img class="d-inline-block align-top" alt="" src="{% static 'todo/Logo.png' %}" height="30" width="30">
          Todo-Project!
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:currenttodos' %}">Current</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:completedtodos' %}">Completed</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link">Logged in as <b>{{ user.username }}</b></a>
          </li>
        </ul>

        <form action="{% url 'todo:logoutuser' %}" method="POST" class="form-inline my-2 my-lg-0">
            {% csrf_token %}
            <button class="btn btn-sm btn-outline-secondary" type="submit">Logout</button>
        </form>
      </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'todo:home' %}">
          <img class="d-inline-block align-top" alt="" src="{% static 'todo/Logo.png' %}" height="30" width="30">
          Todo-Project!
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:currenttodos' %}">Current</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:completedtodos' %}">Completed</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'todo:loginuser' %}">Login</a>
          </li>
          <form action="{% url 'todo:signupuser' %}" method="GET" class="form-inline my-2 my-lg-0">
              {% csrf_token %}
            <button class="btn btn-outline-success" type="submit">Sign Up</button>
          </form>
        </ul>
      </div>
    </nav>
    {% endif %}

    {% block content %}

    {% endblock %}
</body>
</html>

todo/templates/todo/completedtodos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Completed Todos</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>
    {% block content %}
    <h1>Completed Todos</h1>
    <ul>
        {% for todo in todos %}
        <li>
            <a href="{% url 'todo:viewtodo' todo.id %}">
                {% if todo.important %}
                    <b>{{ todo.title }}</b>
                {% else %}
                    {{ todo.title }}
                {% endif %}
                {% if todo.memo %}
                    - {{ todo.memo|truncatechars:30 }}
                {% endif %}
                {{ todo.datecompleted|date:'M j Y H:i' }}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

todo/templates/todo/createtodo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Todo</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>
    {% block content %}
    <h1>Create Todo</h1>
    <h2>{{ error }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    {% endblock %}
</body>
</html>

todo/templates/todo/currenttodos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Current Todos</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>
{% block content %}
    <h1>Current Todos</h1>
    <ul>
        {% for todo in todos %}
        <li>
            <a href="{% url 'todo:viewtodo' todo.id %}">
                {% if todo.important %}
                    <b>{{ todo.title }}</b>
                {% else %}
                    {{ todo.title }}
                {% endif %}
                {% if todo.memo %}
                    - {{ todo.memo|truncatechars:30 }}
                {% endif %}
            </a>
        </li>
        {% endfor %}
    </ul>
    <form method="GET" action="{% url 'todo:createtodo' %}">
        {% csrf_token %}
        <button type="submit">Create new ToDo</button>
    </form>
{% endblock %}
</body>
</html>

todo/templates/todo/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo Project - Home</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>
    {% block content %}
    <h1>Todo Project!</h1>
    <h5>Create your To-Dos!</h5>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'home' %}">Back to portfolio</a>


    {% endblock %}
</body>
</html>

todo/templates/todo/loginuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>
    {% block content %}
    <h1>Log In</h1>
    <h2>{{ error }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    {% endblock %}
</body>
</html>

todo/templates/todo/signupuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>
    {% block content %}
    <h1>Sign Up</h1>
    <h2>{{ error }}</h2>
    <form method="POST">
        {% csrf_token %}
        <p>Username: {{ form.username }}</p>
        <p>Password: {{ form.password1 }}</p>
        <p>Confirm your password: {{ form.password2 }}</p>
        <button type="submit">Sign Up</button>
    </form>
    {% endblock %}
</body>
</html>

todo/templates/todo/viewtodo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Todo</title>
    {% extends 'todo/base.html' %}
    {% load static %}
</head>
<body>

    {% block content %}
    {{ error }}
    <h1>View Todo</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <form method="POST" action="{% url 'todo:completetodo' todo.id %}">
        {% csrf_token %}
        <button type="submit">Complete</button>
    </form>
    <form method="POST" action="{% url 'todo:deletetodo' todo.id %}">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>

{% endblock %}
</body>
</html>