blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('password-generator/', include("pwgenerator.urls"), name='pwgenerator'),
    path('todo/', include("todo.urls"), name='todo'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pwgenerator/urls.py
from django.urls import path
from . import views

app_name = 'pwgenerator'

urlpatterns = [
    path('', views.home, name='home'),
    path('password/', views.password, name='password'),
    path('error/', views.password, name='passworderror')
]

pwgenerator/models.py
from django.db import models

# Create your models here.

pwgenerator/views.py
from django.shortcuts import render
import random
from django.http import HttpResponse
# Create your views here.

def home(request):
    return render(request, 'pwgenerator/home.html')

def password(request):
    characters = []

    if request.GET.get('lowercase'):
        characters.extend(list('abcdefghijklmnopqrstuvwxyz'))
    if request.GET.get('uppercase'):
        characters.extend(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'))
    if request.GET.get('numbers'):
        characters.extend(list('0123456789'))
    if request.GET.get('specialchars'):
        characters.extend(list('!@#$%&*'))

    length = int(request.GET.get('length', 10))  # default value = 10
    thepassword = ''

    if not len(characters):
        return render(request, 'pwgenerator/passworderror.html')
    for eachChar in range(length):
        thepassword += random.choice(characters)

    return render(request, 'pwgenerator/password.html', {'password': thepassword})

pwgenerator/templates/pwgenerator/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>PW Generator</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container text-center">
        <h1>Password Generator by Ebert</h1>
        <form action="{% url 'pwgenerator:password' %}"> <!-- ao clicar submit, vai para a url referenciada pelo nome 'password' em urls.py-->
            <select name="length">
                <option value="6">6 length</option>
                <option value="7">7 length</option>
                <option value="8">8 length</option>
                <option value="9">9 length</option>
                <option value="10" selected="selected">10 length</option>
                <option value="11">11 length</option>
                <option value="12">12 length</option>
                <option value="13">13 length</option>
                <option value="14">14 length</option>
                <option value="15">15 length</option>
                <option value="16">16 length</option>
                <option value="17">17 length</option>
                <option value="18">18 length</option>
                <option value="19">19 length</option>
                <option value="20">20 length</option>
            </select> Length
            <br>
            <input type="checkbox" name="uppercase"> Uppercase
            <br>
            <input type="checkbox" name="lowercase"> Lowercase
            <br>
            <input type="checkbox" name="numbers"> Numbers
            <br>
            <input type="checkbox" name="specialchars"> Special Characters
            <br>
            <input type="submit" value="Submit" class="btn btn-primary">
            <br>
            <br>
            <a href="{% url 'home' %}" class="btn btn-info">Back to Portfolio</a>
        </form>
    </div>
</body>
</html>

pwgenerator/templates/pwgenerator/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PW Generator</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container text-center">
        <h1>Your password is:</h1>
        <h2 class="alert alert-success" id="password">{{ password }}</h2>
        <button class='btn btn-success' onclick="copyToClipboard()">Copy Password</button>
        <br>
        <br>
        <a href="{% url 'pwgenerator:home' %}" class="btn btn-warning">New Password</a>
        <br>
        <br>
        <a href="{% url 'home' %}" class="btn btn-info">Back to Portfolio</a>
    </div>
</body>
<script>
    function copyToClipboard(){
        var copyText = document.getElementById("password").innerText;
        var elem = document.createElement("textarea");
        document.body.appendChild(elem);
        elem.value = copyText;
        elem.select();

        document.execCommand("copy");
        document.body.removeChild(elem);
        alert("Password copied to clipboard: " + elem.value);
    }
</script>
</html>

pwgenerator/templates/pwgenerator/passworderror.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Error!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
<!--    <a href="{% url 'home' %}">Voltar</a>-->
</body>
</html>

<script type="text/javascript">
  alert("Selecione pelo menos uma opção para criar seu password");
  window.location.href = '{% url 'pwgenerator:home' %}';
</script>